[project]
name = "command-center"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.133.0",
    "httpx>=0.28.1",
    "reflex>=0.8.27",
    "uvicorn>=0.41.0",
]
